AppName: "gin web demo"
appport: 9100
appversion: "1.0.0"
timezone: "Asia/Shanghai"
httpLimiter: 1
RunMode: "debug"

# 日志配置
log:
  dir: "./log"
  level: "DEBUG"
  toFile: true
  maxsize: 1
  maxAge: 1
  maxBackups: 3
  compress: false

mysql:
  default: {
      host: "127.0.0.1",
      port: 3306,
      user: "root",
      password: "123456",
      database: "test",
      charset: "utf8mb4",
      tablePre: "",
      #连接池配置
      maxNum: 10,
      minNum: 2,
    }

redis:
  default: {
      host: "127.0.0.1",
      port: 6378,
      auth: "",
      db: 0,
      #连接池配置
      maxNum: 10,
      minNum: 2,
    }

grpc:
  host: "127.0.0.1"
  port: 9090
warnbot:
  wx: "" 
